// src/components/payments/data.ts
import { type Payment } from "./columns";

export const data: Payment[] = [
  { id: "m5gr84i9", amount: 316, status: "success", email: "ken99@yahoo.com" },
  { id: "3u1reuv4", amount: 242, status: "success", email: "Abe45@gmail.com" },
  {
    id: "derv1ws0",
    amount: 837,
    status: "processing",
    email: "Monserrat44@gmail.com",
  },
  {
    id: "5kma53ae",
    amount: 874,
    status: "success",
    email: "Silas22@gmail.com",
  },
  {
    id: "bhqecj4p",
    amount: 721,
    status: "failed",
    email: "carmella@hotmail.com",
  },
  { id: "3u1reuv5", amount: 132, status: "success", email: "Abe46@gmail.com" },
  {
    id: "derv1ws1",
    amount: 937,
    status: "processing",
    email: "Monserrat45@gmail.com",
  },
  {
    id: "5kma53af",
    amount: 974,
    status: "success",
    email: "Silas23@gmail.com",
  },
  {
    id: "bhqecj4q",
    amount: 821,
    status: "failed",
    email: "carmella2@hotmail.com",
  },
  { id: "m5gr84i0", amount: 416, status: "success", email: "ken98@yahoo.com" },
  { id: "3u1reuv6", amount: 342, status: "success", email: "Abe47@gmail.com" },
  {
    id: "derv1ws2",
    amount: 737,
    status: "processing",
    email: "Monserrat46@gmail.com",
  },
  {
    id: "5kma53ag",
    amount: 774,
    status: "success",
    email: "Silas24@gmail.com",
  },
  {
    id: "bhqecj4r",
    amount: 621,
    status: "failed",
    email: "carmella3@hotmail.com",
  },
  { id: "m5gr84i1", amount: 516, status: "success", email: "ken97@yahoo.com" },
  { id: "3u1reuv7", amount: 442, status: "success", email: "Abe48@gmail.com" },
  {
    id: "derv1ws3",
    amount: 637,
    status: "processing",
    email: "Monserrat47@gmail.com",
  },
  {
    id: "5kma53ah",
    amount: 674,
    status: "success",
    email: "Silas25@gmail.com",
  },
  {
    id: "bhqecj4s",
    amount: 521,
    status: "failed",
    email: "carmella4@hotmail.com",
  },
  { id: "m5gr84i2", amount: 616, status: "success", email: "ken96@yahoo.com" },
  { id: "3u1reuv8", amount: 542, status: "success", email: "Abe49@gmail.com" },
  {
    id: "derv1ws4",
    amount: 537,
    status: "processing",
    email: "Monserrat48@gmail.com",
  },
  {
    id: "5kma53ai",
    amount: 574,
    status: "success",
    email: "Silas26@gmail.com",
  },
  {
    id: "bhqecj4t",
    amount: 421,
    status: "failed",
    email: "carmella5@hotmail.com",
  },
  { id: "m5gr84i3", amount: 716, status: "success", email: "ken95@yahoo.com" },
  { id: "3u1reuv9", amount: 642, status: "success", email: "Abe50@gmail.com" },
  {
    id: "derv1ws5",
    amount: 437,
    status: "processing",
    email: "Monserrat49@gmail.com",
  },
  {
    id: "5kma53aj",
    amount: 474,
    status: "success",
    email: "Silas27@gmail.com",
  },
  {
    id: "bhqecj4u",
    amount: 321,
    status: "failed",
    email: "carmella6@hotmail.com",
  },
  { id: "m5gr84i4", amount: 816, status: "success", email: "ken94@yahoo.com" },
  { id: "3u1reuv0", amount: 742, status: "success", email: "Abe51@gmail.com" },
  {
    id: "derv1ws6",
    amount: 337,
    status: "processing",
    email: "Monserrat50@gmail.com",
  },
  {
    id: "5kma53ak",
    amount: 374,
    status: "success",
    email: "Silas28@gmail.com",
  },
  {
    id: "bhqecj4v",
    amount: 221,
    status: "failed",
    email: "carmella7@hotmail.com",
  },
  { id: "m5gr84i5", amount: 916, status: "success", email: "ken93@yahoo.com" },
  { id: "3u1reuv1", amount: 842, status: "success", email: "Abe52@gmail.com" },
  {
    id: "derv1ws7",
    amount: 237,
    status: "processing",
    email: "Monserrat51@gmail.com",
  },
  {
    id: "5kma53al",
    amount: 274,
    status: "success",
    email: "Silas29@gmail.com",
  },
  {
    id: "bhqecj4w",
    amount: 121,
    status: "failed",
    email: "carmella8@hotmail.com",
  },
  { id: "m5gr84i6", amount: 116, status: "success", email: "ken92@yahoo.com" },
  { id: "3u1reuv2", amount: 942, status: "success", email: "Abe53@gmail.com" },
  {
    id: "derv1ws8",
    amount: 137,
    status: "processing",
    email: "Monserrat52@gmail.com",
  },
  {
    id: "5kma53am",
    amount: 174,
    status: "success",
    email: "Silas30@gmail.com",
  },
  {
    id: "bhqecj4x",
    amount: 921,
    status: "failed",
    email: "carmella9@hotmail.com",
  },
  { id: "m5gr84i7", amount: 216, status: "success", email: "ken91@yahoo.com" },
  { id: "3u1reuv3", amount: 142, status: "success", email: "Abe54@gmail.com" },
  {
    id: "derv1ws9",
    amount: 997,
    status: "processing",
    email: "Monserrat53@gmail.com",
  },
  {
    id: "5kma53an",
    amount: 994,
    status: "success",
    email: "Silas31@gmail.com",
  },
  {
    id: "bhqecj4y",
    amount: 981,
    status: "failed",
    email: "carmella10@hotmail.com",
  },
  { id: "m5gr84i8", amount: 450, status: "pending", email: "test@example.com" },
];
